"""Write configs/hf_m0.yaml and configs/hf_m1.yaml for the imperfect-prior study
(docs/PLAN_HIGH_FIDELITY.md) from configs/default.yaml.

Scales: S_x keeps the single-track values for the body states, the input bounds for the actuator states
(6000 N, 0.3 rad) and the 99th percentile of |slip velocity| over the training distribution for the
wheel states; S_f is the standard deviation of the PRIOR's rates (the physics the residual compares
against, as for the single-track model) over driving states x uniform inputs.  Training budget from
E11/E12: 300 Adam epochs at a constant learning rate + 2000 L-BFGS iterations, 10k collocation points,
half of them log-spaced in time near t = 0 (wheel-slip transient).  Run once; the files are committed.

    python scripts/make_hf_configs.py [--n 20000]
"""
import argparse
import os
import sys

import numpy as np
import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pinc import data_hf, plant_hf, prior_hf  # noqa: E402
from pinc.config import DEFAULT_CONFIG_PATH, ROOT, load_config  # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument("--n", type=int, default=20000)
a = ap.parse_args()

base = load_config()
with open(DEFAULT_CONFIG_PATH) as fh:
    d0 = yaml.safe_load(fh)
q = prior_hf.nominal_params(base.params)
for variant in ("M0", "M1"):
    p = plant_hf.make_params(base.params, variant)
    s = data_hf.driving_states(a.n, 12345, p, tuple(base.box_train.vx), base.u_min, base.u_max)
    u = np.random.default_rng(12346).uniform(base.u_min, base.u_max, (len(s), 2))
    S_f = prior_hf.f_s(s, u, q).std(axis=0)
    sig_scale = float(np.round(np.percentile(np.abs(s[:, 6:10]), 99), 2))
    d = dict(d0)
    d["system"] = f"hf_{variant.lower()}"
    d["scales"] = dict(S_x=[30.0, 1.5, 0.6, 0.5, 6000.0, 0.3] + [sig_scale]*4, S_u=[6000.0, 0.3],
                       S_f=[float(f"{v:.4g}") for v in S_f])
    d["loss"] = dict(d0["loss"], residual_mask=[1]*10)
    d["train"] = dict(d0["train"], lr_decay="none", lbfgs_iters=2000, n_colloc=10000, colloc_log_frac=0.5)
    d["sim"] = dict(d0["sim"], dt_plant=plant_hf.DT_PLANT,
                    noise_sigma=list(d0["sim"]["noise_sigma"]) + [0.5]*4 + [50.0, 0.001],
                    x0_sigma=list(d0["sim"]["x0_sigma"]) + [0.0]*6)
    d["mpc"] = dict(d0["mpc"], dt_pred=plant_hf.DT_PRED)
    out = os.path.join(ROOT, "configs", f"hf_{variant.lower()}.yaml")
    with open(out, "w") as fh:
        fh.write(f"# Imperfect-prior study, variant {variant} (docs/PLAN_HIGH_FIDELITY.md).  Generated by "
                 f"scripts/make_hf_configs.py (n = {a.n}, seeds 12345/12346) -- regenerate, do not edit.\n"
                 "# Measurement noise on the extra plant states [w_fl, w_fr, w_rl, w_rr, F_act, delta_act]: wheel-speed "
                 "encoders 0.5 rad/s, drive-force estimate 50 N, steering-angle sensor 0.001 rad.\n")
        yaml.safe_dump(d, fh, sort_keys=False, default_flow_style=None)
    print("wrote", out, "S_f", d["scales"]["S_f"], "sig scale", sig_scale)
    load_config(out)                                  # validates sizes against the system
